name: colored_note

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ">=3.2.6 <4.0.0"
    dependencies:
      flutter_quill: ^9.3.3
      uuid: ^4.3.3
    dev_dependencies:
      flutter_lints: ^3.0.1

scripts:
  analyze:
    exec: dart analyze .
