arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: folder_list_localizations.dart
output-class: FolderListLocalizations
synthetic-package: false
nullable-getter: false
