# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

KEYCHAIN_NAME = "fastlane_keychain_login"
KEYCHAIN_PASSWORD = "200489ppA"

platform :ios do

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false
    )
  end

  desc "Check certs and profiles"
  lane :prepare_signing do |options|
    app_id = "dev.sihuynh.colored-note"

    create_keychain(
      name: KEYCHAIN_NAME,
      password: KEYCHAIN_PASSWORD,
      default_keychain: false,
      unlock: true,
      timeout: 3600
    )

    match(
      app_identifier: [app_id],
      type: "appstore",
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_AUTHORIZATION"],
      username: ENV["FASTLANE_USER"],
      readonly: true
    )
  end

  desc "Build the iOS app"
  lane :build_and_submit do
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    sh("cd ../.. && flutter build ipa -t lib/main.dart --release")

    deliver(
      api_key: api_key,
      ipa: '../build/ios/ipa/colored_note.ipa',
      skip_screenshots: true,
      skip_metadata: true,
      skip_app_version_update: true,
      force: true,
      run_precheck_before_submit: false 
    )

    dsym_zip(
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )

  end

  desc "Push a new beta build to TestFlight"
  lane :deploy do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    prepare_signing
    build_and_submit
  end
end
