name: folder_repository
publish_to: none

environment:
    sdk: ">=3.0.6 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    domain_models:
        path: ../domain_models
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    key_value_storage:
        path: ../key_value_storage
    uuid: ^3.0.7

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
